Use available clang-format version
ethz-asl/grid_map_geo pull request #45
Opened 2024-01-17 04:13 UTC by Ryanf55

# Purpose

ROS2 (on humble) comes with clang-format 14, but the scripts hard code clang-format 6. 

# Risk

We don't yet check this in CI, but we should. I'll add a job for it. Note - running version 14 results in the following diff (small):
```
ryan@B650-970:~/Dev/ros2_ws/src/grid_map_geo/Tools$ ./check_code_format.sh 
diff --git a/include/grid_map_geo/grid_map_geo.hpp b/include/grid_map_geo/grid_map_geo.hpp
index 7d293b6..6e98f78 100644
--- a/include/grid_map_geo/grid_map_geo.hpp
+++ b/include/grid_map_geo/grid_map_geo.hpp
@@ -37,2 +36,0 @@
-#include "grid_map_geo/transform.hpp"
-
@@ -41,0 +40,2 @@
+#include "grid_map_geo/transform.hpp"
+
diff --git a/src/test_tif_loader.cpp b/src/test_tif_loader.cpp
index a1dddc4..4951269 100644
--- a/src/test_tif_loader.cpp
+++ b/src/test_tif_loader.cpp
@@ -41,4 +40,0 @@
-
-#include "rclcpp/rclcpp.hpp"
-#include "std_msgs/msg/string.hpp"
-
@@ -46,0 +43,2 @@
+#include "rclcpp/rclcpp.hpp"
+#include "std_msgs/msg/string.hpp"
diff --git a/test/test_grid_map_geo.cpp b/test/test_grid_map_geo.cpp
index cb1c005..738be37 100644
--- a/test/test_grid_map_geo.cpp
+++ b/test/test_grid_map_geo.cpp
@@ -1,2 +0,0 @@
-#include "grid_map_geo/transform.hpp"
-
@@ -3,0 +2 @@
+
@@ -5,0 +5,2 @@
+#include "grid_map_geo/transform.hpp"
+
Code style check failed, please run clang-format (e.g. with scripts/fix_code_style.sh)
```

2024-01-17 10:18 UTC, Jaeyoung-Lim requested changes
Thanks for fixing this!

Was meaning to do this for a while now.

Would be great if you could rebase?

2024-01-17 14:43 UTC, Ryanf55 commented
> Thanks for fixing this!
> 
> Was meaning to do this for a while now.
> 
> Would be great if you could rebase?

Done! Conflicts are resolved.

2024-01-17 20:43 UTC, Ryanf55 commented
> @Ryanf55 Any ideas for the build failures

Oops, yep. I'll put it in draft and re-request review when it's fixed.

2024-01-20 06:36 UTC, Ryanf55 commented
Ready for final review. Let's try to get this in soon to fix all the style problems and enforce clean diffs after this.

2024-01-20 07:32 UTC, Jaeyoung-Lim approved these changes
LGTM! Thanks!

2024-01-20 07:33 UTC, merged